
//PAGES
export const FETCH_PAGES = 'FETCH_PAGES';
export const FETCH_PAGES_FULFILLED = 'FETCH_PAGES_FULFILLED';
export const FETCH_PAGES_REJECTED = 'FETCH_PAGES_REJECTED';

//POSTS
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

//SINGLE POST
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_SINGLE_POST_FULFILLED = 'FETCH_SINGLE_POST_FULFILLED';
export const FETCH_SINGLE_POST_REJECTED = 'FETCH_SINGLE_POST_REJECTED';

