
//PAGES
export const FETCH_LATEST = 'FETCH_LATEST';
export const FETCH_LATEST_FULFILLED = 'FETCH_LATEST_FULFILLED';
export const FETCH_LATEST_REJECTED = 'FETCH_LATEST_REJECTED';

//POSTS
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

//SINGLE POST
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_SINGLE_POST_FULFILLED = 'FETCH_SINGLE_POST_FULFILLED';
export const FETCH_SINGLE_POST_REJECTED = 'FETCH_SINGLE_POST_REJECTED';

//SINGLE REGION
export const FETCH_SINGLE_REGION = 'FETCH_SINGLE_REGION';
export const FETCH_SINGLE_REGION_FULFILLED = 'FETCH_SINGLE_REGION_FULFILLED';
export const FETCH_SINGLE_REGION_REJECTED = 'FETCH_SINGLE_REGION_REJECTED';

